# Generated by Django 3.1.8 on 2021-06-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('album', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
